platform :ios, "7.0"
workspace 'Examples.xcworkspace'
xcodeproj 'Examples.xcodeproj'
pod 'Reveal-iOS-SDK'
pod 'TLIndexPathTools', '~> 0.3.0'
pod 'TuneKit', :path => '..'
pod 'RBBAnimation', :git => 'https://github.com/robb/RBBAnimation.git', :tag => 'v0.4.0'
